name: Server Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read
  statuses: write
  packages: write

env:
  TUIST_CONFIG_TOKEN: ${{ secrets.TUIST_CONFIG_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MISE_SOPS_AGE_KEY: ${{ secrets.MISE_SOPS_AGE_KEY }}
  MISE_EXPERIMENTAL: "1"
  PNPM_HOME: ~/.pnpm

jobs:
  release:
    name: Release Server
    runs-on: namespace-profile-default
    timeout-minutes: 60
    if: ${{ !contains(github.event.head_commit.message, '[Release] Tuist Server') }}
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.TUIST_GITHUB_TOKEN }}
      - name: Restore Mix Cache
        uses: actions/cache@v3
        id: mix-cache
        with:
          path: |
            deps
            _build
            _site
          key: mix-${{ hashFiles('mix.lock') }}
      - name: Restore PNPM Cache
        uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: |
            ~/.pnpm/store
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - uses: tuist/mise-action@18966898ea274fb74c1d7cf9cc1758fe0d9ddc7e
        with:
          version: 2025.7.0
          experimental: true

      - name: Check if there are releasable changes
        id: is-releasable
        run: |
          # Get the latest server version tag
          LATEST_VERSION=$(git tag -l | grep "server@" | sort -V | tail -n1)

          if [ -n "$LATEST_VERSION" ]; then
            # Use git cliff to determine next version from the latest tag
            NEXT_VERSION=$(git cliff --include-path "server/**/*" --config cliff.toml --repository "../" --bumped-version 2>/dev/null -- ${LATEST_VERSION}..HEAD)
          else
            # No server tags exist, use git cliff without range
            NEXT_VERSION=$(git cliff --include-path "server/**/*" --config cliff.toml --repository "../" --bumped-version 2>/dev/null)
          fi

          # Add server@ prefix if not present
          if [[ "$NEXT_VERSION" != server@* ]]; then
            NEXT_VERSION="server@$NEXT_VERSION"
          fi

          echo "Latest version: ${LATEST_VERSION:-none}"
          echo "Next version: $NEXT_VERSION"

          # Compare versions to determine if release is needed
          if [ "$LATEST_VERSION" != "$NEXT_VERSION" ]; then
            echo "Version bump detected: $LATEST_VERSION -> $NEXT_VERSION"
            echo "should-release=true" >> $GITHUB_ENV
          else
            echo "No version change detected"
            echo "should-release=false" >> $GITHUB_ENV
          fi

      - name: Exit if no release needed
        if: env.should-release == 'false'
        run: |
          echo "No releasable changes found. Exiting."
          exit 0

      - name: Get next version
        id: next-version
        if: env.should-release == 'true'
        run: |
          # Get the latest server version tag
          LATEST_VERSION=$(git tag -l | grep "server@" | sort -V | tail -n1)

          if [ -n "$LATEST_VERSION" ]; then
            # Use git cliff to determine next version from the latest tag
            NEXT_VERSION=$(git cliff --include-path "server/**/*" --config cliff.toml --repository "../" --bumped-version 2>/dev/null -- ${LATEST_VERSION}..HEAD)
          else
            # No server tags exist, use git cliff without range
            NEXT_VERSION=$(git cliff --include-path "server/**/*" --config cliff.toml --repository "../" --bumped-version 2>/dev/null)
          fi

          # Add server@ prefix if not present
          if [[ "$NEXT_VERSION" != server@* ]]; then
            NEXT_VERSION="server@$NEXT_VERSION"
          fi

          echo "NEXT_VERSION=$NEXT_VERSION" >> "$GITHUB_OUTPUT"
          # Extract just the version number without the 'server@' prefix for Docker tags
          echo "NEXT_VERSION_NUMBER=${NEXT_VERSION#server@}" >> "$GITHUB_OUTPUT"
          echo "Next version: $NEXT_VERSION"

      - name: Get release notes
        id: release-notes
        if: env.should-release == 'true'
        run: |
          # Get the latest server version tag
          LATEST_VERSION=$(git tag -l | grep "server@" | sort -V | tail -n1)

          echo "RELEASE_NOTES<<EOF" >> "$GITHUB_OUTPUT"
          if [ -n "$LATEST_VERSION" ]; then
            git cliff --include-path "server/**/*" --config cliff.toml --repository "../" --unreleased 2>/dev/null -- ${LATEST_VERSION}..HEAD >> "$GITHUB_OUTPUT"
          else
            git cliff --include-path "server/**/*" --config cliff.toml --repository "../" --unreleased 2>/dev/null >> "$GITHUB_OUTPUT"
          fi
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Update CHANGELOG.md
        if: env.should-release == 'true'
        run: |
          # Get the latest server version tag
          LATEST_VERSION=$(git tag -l | grep "server@" | sort -V | tail -n1)

          if [ -n "$LATEST_VERSION" ]; then
            git cliff --include-path "server/**/*" --config cliff.toml --repository "../" --bump -o CHANGELOG.md 2>/dev/null -- ${LATEST_VERSION}..HEAD
          else
            git cliff --include-path "server/**/*" --config cliff.toml --repository "../" --bump -o CHANGELOG.md 2>/dev/null
          fi

      - name: Login to GitHub Container Registry
        if: env.should-release == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Image metadata
        id: meta
        if: env.should-release == 'true'
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/tuist/tuist
          flavor: |
            latest=true
          tags: |
            type=raw,value=${{ steps.next-version.outputs.NEXT_VERSION_NUMBER }}
            type=raw,value=latest
          labels: |
            org.opencontainers.image.title=Tuist
            org.opencontainers.image.vendor=Tuist GmbH
            org.opencontainers.image.source=https://github.com/tuist/tuist

      - name: Build and push
        if: env.should-release == 'true'
        uses: docker/build-push-action@v6
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            TUIST_HOSTED=0
            TUIST_VERSION=${{ steps.next-version.outputs.NEXT_VERSION_NUMBER }}
            MIX_ENV=prod
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Commit changes
        if: env.should-release == 'true'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add CHANGELOG.md
          git commit -m "[Release] Tuist Server ${{ steps.next-version.outputs.NEXT_VERSION }}"
          git tag ${{ steps.next-version.outputs.NEXT_VERSION }}

          # Pull and rebase to avoid conflicts from concurrent releases
          max_attempts=5
          attempt=1
          while [ $attempt -le $max_attempts ]; do
            echo "Attempt $attempt of $max_attempts"
            if git pull --rebase origin ${{ github.ref_name }}; then
              if git push origin ${{ github.ref_name }} && git push origin ${{ steps.next-version.outputs.NEXT_VERSION }}; then
                echo "Successfully pushed changes"
                break
              fi
            fi
            echo "Push failed, retrying in 5 seconds..."
            sleep 5
            attempt=$((attempt + 1))
          done

          if [ $attempt -gt $max_attempts ]; then
            echo "Failed to push after $max_attempts attempts"
            exit 1
          fi

      - name: Create GitHub Release
        if: env.should-release == 'true'
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          repository: tuist/tuist
          name: ${{ steps.next-version.outputs.NEXT_VERSION }}
          tag_name: ${{ steps.next-version.outputs.NEXT_VERSION }}
          body: |
            ## Server Release

            ${{ steps.release-notes.outputs.RELEASE_NOTES }}
